# Generated by Django 3.0.2 on 2020-02-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200207_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='requested_price',
            field=models.TextField(default=10),
        ),
    ]
